### ISSUE TITLE
用户名 密码 是什么

### ISSUE THREAD

**Issue by AntoniaQiao** [xgtxxxx/odoo-angular2-demo-#1]

**Comment by xgtxxxx** [comment]
如果你前后台一起启动的话，你需要配置你的redis. 如果你是只启动前端app，那么你需要修改下app.service.ts文件，把这里面向后台请求的方法全部修改成模拟数据就可以了。

**Comment by xgtxxxx** [comment]
如果你前后台一起启动的话，你需要配置你的redis. 如果你是只启动前端app，那么你需要修改下app.service.ts文件，把这里面向后台请求的方法全部修改成模拟数据就可以了。
